### 1. For $A = \begin{bmatrix}3 & 1\\5 & 2\end{bmatrix}$, compute $\det(A)$ and $A^{-1}$ by hand, then verify using NumPy.


Given,

$$
A =
\begin{bmatrix}
3 & 1\\
5 & 2
\end{bmatrix}
$$

$$
\det(A) = (3)(2) - (1)(5)
$$

$$
= 6 - 5
$$

$$
\det(A) = 1 \neq 0
$$

Therefore, inverse exists.

$$
A^{-1} = \frac{1}{\det(A)}\operatorname{adj}(A)
$$

$$
= \frac{1}{1}
\begin{bmatrix}
2 & -1\\
-5 & 3
\end{bmatrix}
$$

Therefore,

$$
A^{-1} =
\begin{bmatrix}
2 & -1\\
-5 & 3
\end{bmatrix}
$$

In [1]:
import numpy as np

A = np.array([[3, 1],
              [5, 2]])

det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print("det(A) =", det_A)
print("A^(-1) =\n", inv_A)

det(A) = 1.0000000000000009
A^(-1) =
 [[ 2. -1.]
 [-5.  3.]]


### 2. Solve $3x+y=7$, $x+2y=5$ and check the residual.

Given,

$$
\begin{bmatrix}
3 & 1\\
1 & 2
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
7\\
5
\end{bmatrix}
$$

Let,

$$
A=
\begin{bmatrix}
3 & 1\\
1 & 2
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
7\\
5
\end{bmatrix}
$$

$$
X=A^{-1}B
$$

First,

$$
|A|=(3)(2)-(1)(1)
$$

$$
=6-1=5
$$

Therefore,

$$
A^{-1}
=
\frac{1}{5}
\begin{bmatrix}
2 & -1\\
-1 & 3
\end{bmatrix}
$$

Now,

$$
X=
\frac{1}{5}
\begin{bmatrix}
2 & -1\\
-1 & 3
\end{bmatrix}
\begin{bmatrix}
7\\
5
\end{bmatrix}
$$

$$
=
\frac{1}{5}
\begin{bmatrix}
14-5\\
-7+15
\end{bmatrix}
$$

$$
=
\frac{1}{5}
\begin{bmatrix}
9\\
8
\end{bmatrix}
$$

Therefore,

$$
x=1.8,\qquad y=1.6
$$

Residual check:

$$
R=AX-B
$$

$$
=
\begin{bmatrix}
3 & 1\\
1 & 2
\end{bmatrix}
\begin{bmatrix}
1.8\\
1.6
\end{bmatrix}
-
\begin{bmatrix}
7\\
5
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
7\\
5
\end{bmatrix}
-
\begin{bmatrix}
7\\
5
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
0\\
0
\end{bmatrix}
$$

In [2]:
import numpy as np

A = np.array([[3, 1], [1, 2]])
B = np.array([7, 5])

X = np.linalg.solve(A, B)

print(X)
print(A @ X - B)
print(np.linalg.norm(A @ X - B))

[1.8 1.6]
[0. 0.]
0.0


### 3. Find the rank of the matrix

$$
A=
\begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
0 & 1 & 1
\end{bmatrix}
$$


Given,

$$
A=
\begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
0 & 1 & 1
\end{bmatrix}
$$

Apply,

$$
R_2\rightarrow R_2-2R_1
$$

Therefore,

$$
\begin{bmatrix}
1 & 2 & 3\\
0 & 0 & 0\\
0 & 1 & 1
\end{bmatrix}
$$

Now,

$$
R_2\rightarrow R_2
$$

There are $2$ non-zero rows.

Therefore,

$$
\boxed{\operatorname{Rank}(A)=2}
$$

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [2, 4, 6],
              [0, 1, 1]])

print("Rank =", np.linalg.matrix_rank(A))

Rank = 2


### 4. Find the eigenvalues of $\begin{bmatrix}4&0\\0&2\end{bmatrix}$ and verify $Av=\lambda v$.


Given,

$$
A=
\begin{bmatrix}
4 & 0\\
0 & 2
\end{bmatrix}
$$

Characteristic equation:

$$
|A-\lambda I|=0
$$

$$
\begin{vmatrix}
4-\lambda & 0\\
0 & 2-\lambda
\end{vmatrix}=0
$$

$$
(4-\lambda)(2-\lambda)=0
$$

Therefore,

$$
\lambda_1=4,\qquad \lambda_2=2
$$

For $\lambda_1=4$:

$$
(A-\lambda I)v=0
$$

$$
\begin{bmatrix}
4&0\\
0&2
\end{bmatrix}
-
4
\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}
=
\begin{bmatrix}
0&0\\
0&-2
\end{bmatrix}
$$

Therefore,

$$
\begin{bmatrix}
0&0\\
0&-2
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
0\\
0
\end{bmatrix}
$$

$$
y=0
$$

Therefore,

$$
v_1=
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

Verification:

$$
Av_1=
\begin{bmatrix}
4&0\\
0&2
\end{bmatrix}
\begin{bmatrix}
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
4\\
0
\end{bmatrix}
=
4
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

For $\lambda_2=2$:

$$
(A-\lambda I)v=0
$$

$$
\begin{bmatrix}
2&0\\
0&0
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
0\\
0
\end{bmatrix}
$$

$$
x=0
$$

Therefore,

$$
v_2=
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

Verification:

$$
Av_2=
\begin{bmatrix}
4&0\\
0&2
\end{bmatrix}
\begin{bmatrix}
0\\
1
\end{bmatrix}
=
\begin{bmatrix}
0\\
2
\end{bmatrix}
=
2
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

In [4]:
A = np.array([[4, 0],
              [0, 2]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues =", values)
print("Eigenvectors =\n", vectors)

Eigenvalues = [4. 2.]
Eigenvectors =
 [[1. 0.]
 [0. 1.]]


### 5. Perform QR decomposition of $\begin{bmatrix}1&1\\1&-1\end{bmatrix}$ and verify $Q^TQ=I$.

Given,

$$
A=
\begin{bmatrix}
1&1\\
1&-1
\end{bmatrix}
$$

Let,

$$
a_1=
\begin{bmatrix}
1\\
1
\end{bmatrix}
$$

$$
\|a_1\|=\sqrt{1^2+1^2}=\sqrt{2}
$$

Therefore,

$$
q_1=\frac{a_1}{\|a_1\|}
=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
1
\end{bmatrix}
$$

For,

$$
a_2=
\begin{bmatrix}
1\\
-1
\end{bmatrix}
$$

$$
r_{12}=q_1^Ta_2
$$

$$
=
\begin{bmatrix}
\frac{1}{\sqrt2}&\frac{1}{\sqrt2}
\end{bmatrix}
\begin{bmatrix}
1\\
-1
\end{bmatrix}
=0
$$

Therefore,

$$
u_2=a_2-r_{12}q_1=a_2
$$

$$
\|u_2\|=\sqrt{2}
$$

Therefore,

$$
q_2=
\frac{1}{\sqrt2}
\begin{bmatrix}
1\\
-1
\end{bmatrix}
$$

Hence,

$$
Q=
\begin{bmatrix}
\frac1{\sqrt2}&\frac1{\sqrt2}\\
\frac1{\sqrt2}&-\frac1{\sqrt2}
\end{bmatrix}
$$

and

$$
R=
\begin{bmatrix}
\sqrt2&0\\
0&\sqrt2
\end{bmatrix}
$$

Verification:

$$
QR=
\begin{bmatrix}
\frac1{\sqrt2}&\frac1{\sqrt2}\\
\frac1{\sqrt2}&-\frac1{\sqrt2}
\end{bmatrix}
\begin{bmatrix}
\sqrt2&0\\
0&\sqrt2
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
1&1\\
1&-1
\end{bmatrix}
=A
$$

In [5]:
import numpy as np

A = np.array([[1, 1],
              [1, -1]])

Q, R = np.linalg.qr(A)

print("Q =\n", Q)
print("R =\n", R)
print("Q.T @ Q =\n", Q.T @ Q)

Q =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R =
 [[-1.41421356e+00  3.33066907e-16]
 [ 0.00000000e+00 -1.41421356e+00]]
Q.T @ Q =
 [[ 1.00000000e+00 -1.33393446e-16]
 [-1.33393446e-16  1.00000000e+00]]


### 6. Perform SVD of $\begin{bmatrix}3&0\\4&0\end{bmatrix}$ using the five hand steps shown in class.

### Math Work

Given,

$$
A=
\begin{bmatrix}
3&0\\
4&0
\end{bmatrix}
$$

### Step 1: Find $A^TA$

$$
A^T=
\begin{bmatrix}
3&4\\
0&0
\end{bmatrix}
$$

$$
A^TA=
\begin{bmatrix}
3&4\\
0&0
\end{bmatrix}
\begin{bmatrix}
3&0\\
4&0
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
25&0\\
0&0
\end{bmatrix}
$$

### Step 2: Find eigenvalues

$$
|A^TA-\lambda I|=0
$$

$$
\begin{vmatrix}
25-\lambda&0\\
0&-\lambda
\end{vmatrix}=0
$$

$$
(25-\lambda)(-\lambda)=0
$$

Therefore,

$$
\lambda_1=25,\qquad \lambda_2=0
$$

Singular values:

$$
\sigma_1=\sqrt{25}=5
$$

$$
\sigma_2=\sqrt0=0
$$

Therefore,

$$
\Sigma=
\begin{bmatrix}
5&0\\
0&0
\end{bmatrix}
$$

### Step 3: Find $V$

For $\lambda_1=25$,

$$
v_1=
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

For $\lambda_2=0$,

$$
v_2=
\begin{bmatrix}
0\\
1
\end{bmatrix}
$$

Therefore,

$$
V=
\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}
$$

### Step 4: Find $U$

$$
u_1=\frac{Av_1}{\sigma_1}
$$

$$
=
\frac{1}{5}
\begin{bmatrix}
3&0\\
4&0
\end{bmatrix}
\begin{bmatrix}
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
0.6\\
0.8
\end{bmatrix}
$$

Take,

$$
u_2=
\begin{bmatrix}
-0.8\\
0.6
\end{bmatrix}
$$

Therefore,

$$
U=
\begin{bmatrix}
0.6&-0.8\\
0.8&0.6
\end{bmatrix}
$$

### Step 5: Verification

$$
A=U\Sigma V^T
$$

$$
U\Sigma V^T=
\begin{bmatrix}
0.6&-0.8\\
0.8&0.6
\end{bmatrix}
\begin{bmatrix}
5&0\\
0&0
\end{bmatrix}
\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
3&0\\
4&0
\end{bmatrix}
=A
$$

In [6]:
import numpy as np

A = np.array([[3, 0],
              [4, 0]])

U, S, VT = np.linalg.svd(A)

print("U =\n", U)
print("S =", S)
print("VT =\n", VT)

U =
 [[-0.6 -0.8]
 [-0.8  0.6]]
S = [5. 0.]
VT =
 [[-1. -0.]
 [ 0.  1.]]


### 7. Compute the Cholesky factor of $\begin{bmatrix}9&3\\3&5\end{bmatrix}$.


Given,

$$
A=
\begin{bmatrix}
9&3\\
3&5
\end{bmatrix}
$$

Assume,

$$
L=
\begin{bmatrix}
l_{11}&0\\
l_{21}&l_{22}
\end{bmatrix}
$$

Since,

$$
A=LL^T
$$

Therefore,

$$
\begin{bmatrix}
9&3\\
3&5
\end{bmatrix}
=
\begin{bmatrix}
l_{11}&0\\
l_{21}&l_{22}
\end{bmatrix}
\begin{bmatrix}
l_{11}&l_{21}\\
0&l_{22}
\end{bmatrix}
$$

From the first element,

$$
l_{11}^2=9
$$

$$
l_{11}=3
$$

Next,

$$
l_{21}l_{11}=3
$$

$$
3l_{21}=3
$$

$$
l_{21}=1
$$

Next,

$$
l_{21}^2+l_{22}^2=5
$$

$$
1^2+l_{22}^2=5
$$

$$
l_{22}^2=4
$$

$$
l_{22}=2
$$

Therefore,

$$
L=
\begin{bmatrix}
3&0\\
1&2
\end{bmatrix}
$$

Verification:

$$
LL^T=
\begin{bmatrix}
3&0\\
1&2
\end{bmatrix}
\begin{bmatrix}
3&1\\
0&2
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
9&3\\
3&5
\end{bmatrix}
=A
$$

In [7]:
import numpy as np

A = np.array([[9, 3],
              [3, 5]])

L = np.linalg.cholesky(A)

print("L =\n", L)
print("L @ L.T =\n", L @ L.T)

L =
 [[3. 0.]
 [1. 2.]]
L @ L.T =
 [[9. 3.]
 [3. 5.]]


### 8. Fit a least-squares line to $(1,2),(2,3),(3,4)$ and compare hand calculation with `lstsq`.

Assume,

$$
y=mx+c
$$

Let,

$$
X=
\begin{bmatrix}
1&1\\
2&1\\
3&1
\end{bmatrix},
\qquad
Y=
\begin{bmatrix}
2\\
3\\
4
\end{bmatrix}
$$

Normal equation:

$$
X^TX\beta=X^TY
$$

First,

$$
X^T=
\begin{bmatrix}
1&2&3\\
1&1&1
\end{bmatrix}
$$

Therefore,

$$
X^TX=
\begin{bmatrix}
1&2&3\\
1&1&1
\end{bmatrix}
\begin{bmatrix}
1&1\\
2&1\\
3&1
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
14&6\\
6&3
\end{bmatrix}
$$

Also,

$$
X^TY=
\begin{bmatrix}
1&2&3\\
1&1&1
\end{bmatrix}
\begin{bmatrix}
2\\
3\\
4
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
20\\
9
\end{bmatrix}
$$

Therefore,

$$
\begin{bmatrix}
14&6\\
6&3
\end{bmatrix}
\begin{bmatrix}
m\\
c
\end{bmatrix}
=
\begin{bmatrix}
20\\
9
\end{bmatrix}
$$

Solving,

$$
m=1,\qquad c=1
$$

Therefore,

$$
\boxed{y=x+1}
$$

In [8]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([2, 2, 4])

X = np.column_stack((np.ones(3), x))

b = np.linalg.lstsq(X, y, rcond=None)[0]

print("c =", b[0])
print("m =", b[1])
print("Line: y =", b[1], "x +", b[0])

c = 0.6666666666666669
m = 1.0
Line: y = 1.0 x + 0.6666666666666669


### 9. Explain why $0.1+0.2==0.3$ is false and show the correct comparison.


We know,

$$
0.1+0.2=0.3
$$

But computers store floating-point numbers in binary.

In binary,

$$
0.1=0.0001100110011\ldots
$$

$$
0.2=0.0011001100110\ldots
$$

$$
0.3=0.0100110011001\ldots
$$

These values cannot be represented exactly in binary floating-point.

Therefore,

$$
0.1+0.2\approx0.30000000000000004
$$

So,

$$
0.1+0.2==0.3
$$

is False.

Correct comparison:

$$
\operatorname{isclose}(0.1+0.2,0.3)
$$

This gives True.

In [9]:
import numpy as np

print(np.isclose(0.1 + 0.2, 0.3))

True


### 10. Create arrays of one million values in `float32` and `float64`; compare memory usage.

### 1. Float32

$$
32\text{ bits}=\frac{32}{8}=4\text{ bytes}
$$

Memory:

$$
N\times4
$$

$$
=1,000,000\times4
$$

$$
=4,000,000\text{ bytes}
$$

Convert to MB:

$$
\frac{4,000,000}{1024^2}\approx3.81\text{ MB}
$$

### 2. Float64

$$
64\text{ bits}=\frac{64}{8}=8\text{ bytes}
$$

Memory:

$$
N\times8
$$

$$
=1,000,000\times8
$$

$$
=8,000,000\text{ bytes}
$$

Convert to MB:

$$
\frac{8,000,000}{1024^2}\approx7.63\text{ MB}
$$

Comparison:

$$
\frac{8,000,000}{4,000,000}=2
$$

Therefore,

$$
\boxed{\text{float64 uses twice the memory of float32}}
$$

In [10]:
import numpy as np

a = np.ones(1000000, dtype=np.float32)
b = np.ones(1000000, dtype=np.float64)

print("float32 memory =", a.nbytes, "bytes")
print("float64 memory =", b.nbytes, "bytes")
print("float32 memory:", round(a.nbytes / 1024**2, 2), "MB")
print("float64 memory:", round(b.nbytes / 1024**2, 2), "MB")

float32 memory = 4000000 bytes
float64 memory = 8000000 bytes
float32 memory: 3.81 MB
float64 memory: 7.63 MB


### 11. Compare an $O(n)$ loop with an $O(n^2)$ nested loop using operation counts.


Let,

$$
n=1000
$$

### $O(n)$ loop

$$
\sum_{i=1}^{n}1=n
$$

Therefore,

$$
O(n)\text{ operations}=1000
$$

### $O(n^2)$ nested loop

$$
\sum_{i=1}^{n}\sum_{j=1}^{n}1
$$

$$
=n\times n
$$

$$
=n^2
$$

For $n=1000$,

$$
1000\times1000=1,000,000
$$

Therefore,

$$
O(n^2)\text{ operations}=1,000,000
$$

Comparison:

$$
\frac{O(n^2)}{O(n)}
=
\frac{1,000,000}{1000}
=1000
$$

Therefore,

$$
\boxed{O(n^2)\text{ performs 1000 times more operations}}
$$

In [11]:
#Loop
n = 1000

count1 = 0
for i in range(n):
    count1 += 1

# Nested Loop
count2 = 0
for i in range(n):
    for j in range(n):
        count2 += 1

print("O(n) operations =", count1)
print("O(n^2) operations =", count2)

O(n) operations = 1000
O(n^2) operations = 1000000


### 12. Use bisection to solve $x^3-2=0$ on $[1,2]$ to tolerance $10^{-8}$.

Given,

$$
f(x)=x^3-2
$$

Interval:

$$
[1,2]
$$

Tolerance:

$$
10^{-8}
$$

At $x=1$,

$$
f(1)=1^3-2=-1
$$

At $x=2$,

$$
f(2)=2^3-2=6
$$

Since,

$$
f(1)<0,\qquad f(2)>0
$$

the root lies in $[1,2]$.

Bisection formula:

$$
c=\frac{a+b}{2}
$$

### Iteration 1

$$
c=\frac{1+2}{2}=1.5
$$

$$
f(1.5)=1.5^3-2
$$

$$
=3.375-2=1.375>0
$$

Therefore, root lies between:

$$
[1,1.5]
$$

### Iteration 2

$$
c=\frac{1+1.5}{2}=1.25
$$

$$
f(1.25)=1.25^3-2
$$

$$
=1.953125-2=-0.046875<0
$$

Therefore, root lies between:

$$
[1.25,1.5]
$$

### Iteration 3

$$
c=\frac{1.25+1.5}{2}=1.375
$$

$$
f(1.375)\approx0.5996>0
$$

Therefore, root lies between:

$$
[1.25,1.375]
$$

Continue the bisection process until the interval width is less than

$$
10^{-8}
$$

The root is approximately,

$$
\boxed{x\approx1.25992105}
$$

In [12]:
def f(x):
    return x**3 - 2

a = 1
b = 2
tol = 1e-8

while (b - a) > tol:
    c = (a + b) / 2

    if f(a) * f(c) < 0:
        b = c
    else:
        a = c

print("Root =", (a + b) / 2)
print("Error =", abs(b - a))

Root = 1.2599210478365421
Error = 7.450580596923828e-09


### 13. Approximate $e^x$ at $x=1$ using forward differences for several $h$ values and identify a good range for $h$.

Forward difference formula:

$$
f'(x)\approx\frac{f(x+h)-f(x)}{h}
$$

Given,

$$
f(x)=e^x
$$

and

$$
x=1
$$

Therefore,

$$
f'(x)=e^x
$$

At $x=1$,

$$
f'(1)=e
$$

So,

$$
e\approx\frac{e^{1+h}-e^1}{h}
$$

For $h=0.1$:

$$
f'(1)\approx
\frac{e^{1.1}-e^1}{0.1}
$$

$$
\approx2.85884
$$

For $h=0.01$:

$$
f'(1)\approx
\frac{e^{1.01}-e^1}{0.01}
$$

$$
\approx2.73192
$$

For $h=0.001$:

$$
f'(1)\approx
\frac{e^{1.001}-e^1}{0.001}
$$

$$
\approx2.71964
$$

For $h=0.0001$:

$$
f'(1)\approx
\frac{e^{1.0001}-e^1}{0.0001}
$$

$$
\approx2.71842
$$

Exact value:

$$
e\approx2.71828
$$

As $h$ becomes smaller, the approximation gets closer to $e$.

Therefore, a good range for $h$ is approximately,

$$
\boxed{0.001\text{ to }0.0001}
$$

In [13]:
import numpy as np

x = 1
h_values = [0.1, 0.01, 0.001, 0.0001]

for h in h_values:
    approx = (np.exp(x + h) - np.exp(x)) / h
    print("h =", h, "Approx =", approx)

h = 0.1 Approx = 2.858841954873883
h = 0.01 Approx = 2.7319186557871245
h = 0.001 Approx = 2.7196414225332255
h = 0.0001 Approx = 2.718417747082924
