# Lab 10 – Linear Algebra Computations Using NumPy

## 1. Generator Expression and NumPy Vectorization

### AIM

To calculate a mathematical sum using a generator expression and compare it with NumPy vectorization.

### PROGRAM

In [1]:
import numpy as np

gen_sum = sum(i * i / (i + 1) for i in range(1, 51))
i = np.arange(1, 51)
numpy_sum = np.sum(i * i / (i + 1))

print("Generator sum =", gen_sum)
print("NumPy sum =", numpy_sum)
print("Equal? =", np.isclose(gen_sum, numpy_sum))

Generator sum = 1228.5188131814666
NumPy sum = 1228.5188131814666
Equal? = True


### RESULT

Thus, the given Python program was successfully executed.

## 2. Invertibility, Determinant and Matrix Inverse

### AIM

To check the invertibility of a random 4 × 4 matrix and verify its matrix inverse using NumPy.

### PROGRAM

In [2]:
import numpy as np

A = np.random.rand(4, 4)
det_A = np.linalg.det(A)

print("A =\n", A)
print("det(A) =", det_A)

if abs(det_A) > 1e-10:
    A_inv = np.linalg.inv(A)
    product = np.dot(A, A_inv)
    print("A inverse =\n", A_inv)
    print("A @ A_inverse =\n", product)
    print("Verified?", np.allclose(product, np.eye(4)))
else:
    print("Matrix is singular; inverse does not exist.")

A =
 [[0.92941658 0.68034431 0.31013436 0.97427243]
 [0.42858184 0.25633331 0.45390118 0.66559569]
 [0.699208   0.54005467 0.96755563 0.41022113]
 [0.85842827 0.96149725 0.77688645 0.16005985]]
det(A) = -0.05089174162679042
A inverse =
 [[  4.75807434 -10.09090396   6.83409918  -4.515126  ]
 [ -2.99550696   7.0294254   -6.13791529   4.73314937]
 [ -1.34568288   1.5820225    0.54063227   0.22676263]
 [ -0.99244785   4.21400034  -2.40538264   0.92985783]]
A @ A_inverse =
 [[ 1.00000000e+00 -3.97263227e-16  3.54685230e-16 -1.02616445e-16]
 [-3.69892303e-16  1.00000000e+00 -4.59631271e-17  9.19640173e-17]
 [-3.40027069e-17 -1.77020509e-15  1.00000000e+00 -3.35302843e-16]
 [-3.18194232e-16 -5.56192686e-16 -1.98704119e-16  1.00000000e+00]]
Verified? True


### RESULT

Thus, the given Python program was successfully executed.

## 3. Singular Matrix with Zero Determinant

### AIM

To construct a singular matrix, verify that its determinant is zero, and show that its inverse does not exist.

### PROGRAM

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [2, 4, 6], [1, 1, 1]], dtype=float)
det_A = np.linalg.det(A)

print("A =\n", A)
print("det(A) =", det_A)
print("Numerically zero?", np.isclose(det_A, 0))

if np.isclose(det_A, 0):
    print("A is singular, so A inverse does not exist.")

A =
 [[1. 2. 3.]
 [2. 4. 6.]
 [1. 1. 1.]]
det(A) = 0.0
Numerically zero? True
A is singular, so A inverse does not exist.


### RESULT

Thus, the given Python program was successfully executed.

## 4. Eigenvalues and Eigenvectors

### AIM

To calculate the eigenvalues and eigenvectors of a matrix and verify the relation Av = λv.

### PROGRAM

In [4]:
import numpy as np

A = np.array([[4, 2], [1, 3]], dtype=float)
values, vectors = np.linalg.eig(A)

print("Eigenvalues =", values)
print("Eigenvectors =\n", vectors)

for k in range(len(values)):
    v = vectors[:, k]
    lam = values[k]
    print("\nEigenvalue:", lam)
    print("A v =", np.dot(A, v))
    print("lambda v =", lam * v)
    print("Verified?", np.allclose(np.dot(A, v), lam * v))

Eigenvalues = [5. 2.]
Eigenvectors =
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Eigenvalue: 5.0
A v = [4.47213595 2.23606798]
lambda v = [4.47213595 2.23606798]
Verified? True

Eigenvalue: 2.0
A v = [-1.41421356  1.41421356]
lambda v = [-1.41421356  1.41421356]
Verified? True


### RESULT

Thus, the given Python program was successfully executed.

## 5. Linear System with No Unique Solution

### AIM

To solve an underdetermined linear system using NumPy and identify that it has infinitely many solutions.

### PROGRAM

In [5]:
import numpy as np

A = np.array([[1, 1, 1], [2, 2, 2]], dtype=float)
b = np.array([3, 6], dtype=float)

x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print("One NumPy solution =", x)
print("A @ x =", A @ x)
print("b =", b)
print("Rank(A) =", rank)
print("Residuals =", residuals)

if rank < A.shape[1]:
    print("No unique solution: infinitely many solutions exist.")

One NumPy solution = [1. 1. 1.]
A @ x = [3. 6.]
b = [3. 6.]
Rank(A) = 1
Residuals = []
No unique solution: infinitely many solutions exist.


### RESULT

Thus, the given Python program was successfully executed.

## 6. Rank and Linear Dependence of Rows

### AIM

To calculate the rank of a matrix and identify the linear dependence between its rows.

### PROGRAM

In [6]:
import numpy as np

A = np.array([[1, 2], [2, 4]])
rank_A = np.linalg.matrix_rank(A)

print("A =\n", A)
print("Rank(A) =", rank_A)

if rank_A < min(A.shape):
    print("Rows/columns are linearly dependent.")
    print("Here Row 2 = 2 * Row 1.")

A =
 [[1 2]
 [2 4]]
Rank(A) = 1
Rows/columns are linearly dependent.
Here Row 2 = 2 * Row 1.


### RESULT

Thus, the given Python program was successfully executed.

## 7. Non-Commutativity of Matrix Multiplication

### AIM

To multiply two matrices in both orders and verify that matrix multiplication is generally non-commutative.

### PROGRAM

In [7]:
import numpy as np

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

AB = np.dot(A, B)
BA = np.dot(B, A)

print("A =\n", A)
print("B =\n", B)
print("AB =\n", AB)
print("BA =\n", BA)
print("AB = BA ?", np.allclose(AB, BA))

A =
 [[0.2484201  0.87846819 0.64897117]
 [0.95922309 0.10577928 0.09152279]
 [0.96818681 0.7234047  0.84572553]]
B =
 [[0.90086363 0.92856931 0.14846681]
 [0.42322789 0.80361026 0.729494  ]
 [0.7717854  0.96235208 0.91532544]]
AB =
 [[1.09645134 1.56116008 1.27173924]
 [0.97953389 1.06378759 0.30335129]
 [1.83108795 2.29424972 1.4455771 ]]
BA =
 [[1.25824136 0.99700503 0.79518195]
 [1.5822663  0.98451695 0.96516306]
 [2.00104335 1.44193656 1.36305772]]
AB = BA ? False


### RESULT

Thus, the given Python program was successfully executed.

## 8. Block Diagonal Matrix and Its Determinant

### AIM

To construct a block diagonal matrix and verify that its determinant equals the product of the determinants of its diagonal blocks.

### PROGRAM

In [8]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
Z = np.zeros((2, 2))

M = np.block([[A, Z], [Z, B]])

det_M = np.linalg.det(M)
product = np.linalg.det(A) * np.linalg.det(B)

print("Block matrix M =\n", M)
print("det(M) =", det_M)
print("det(A) det(B) =", product)
print("Verified?", np.isclose(det_M, product))

Block matrix M =
 [[1. 2. 0. 0.]
 [3. 4. 0. 0.]
 [0. 0. 5. 6.]
 [0. 0. 7. 8.]]
det(M) = 4.0000000000000115
det(A) det(B) = 4.000000000000011
Verified? True


### RESULT

Thus, the given Python program was successfully executed.

## 9. Symmetric Matrix and Orthogonal Eigenvectors

### AIM

To calculate the eigenvalues of a symmetric matrix and verify that its eigenvectors are orthogonal.

### PROGRAM

In [9]:
import numpy as np

A = np.array([[2, 1], [1, 2]], dtype=float)
values, vectors = np.linalg.eig(A)

v1 = vectors[:, 0]
v2 = vectors[:, 1]
dot_product = np.dot(v1, v2)

print("Eigenvalues =", values)
print("Eigenvectors =\n", vectors)
print("v1 . v2 =", dot_product)
print("Orthogonal?", np.isclose(dot_product, 0))

Eigenvalues = [3. 1.]
Eigenvectors =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
v1 . v2 = 0.0
Orthogonal? True


### RESULT

Thus, the given Python program was successfully executed.

## 10. Performance: Python Loops versus NumPy Vectorization

### AIM

To compare the execution time of squaring matrix elements using Python loops and NumPy vectorization.

### PROGRAM

In [10]:
import numpy as np
import time

A = np.random.rand(1000, 1000)

start = time.time()
B = A * A
numpy_time = time.time() - start

start = time.time()
C = [[A[i, j] * A[i, j] for j in range(1000)] for i in range(1000)]
loop_time = time.time() - start

print("NumPy time =", numpy_time, "seconds")
print("Loop time =", loop_time, "seconds")
print("Same result?", np.allclose(B, np.array(C)))

if numpy_time > 0:
    print("Speed-up factor =", loop_time / numpy_time)

NumPy time = 0.003256082534790039 seconds
Loop time = 0.7316958904266357 seconds
Same result? True
Speed-up factor = 224.71662883502967


### RESULT

Thus, the given Python program was successfully executed.