# Lab 9 – Advanced Numerical Simulation and Statistical Analysis


## 1. Random Sensor Readings and Normalization

### AIM

To generate 1000 random sensor readings using a generator expression and normalize the readings using the mean and standard deviation.

### PROGRAM

In [1]:
import numpy as np

# Generate 1000 random numbers
data = np.fromiter((np.random.rand() for _ in range(1000)), dtype=float)

# Compute mean and standard deviation of original data
mean = np.mean(data)
std = np.std(data)

# Normalize the data
normalized = (data - mean) / std

# Print results
print("Original Mean =", mean)
print("Original Standard Deviation =", std)
print("Normalized Data =", normalized)

# Check mean and std of normalized data
print("Normalized Mean =", np.mean(normalized))
print("Normalized Standard Deviation =", np.std(normalized))
print(np.isclose(np.mean(normalized), 0))
print(round(np.mean(normalized), 10))

Original Mean = 0.4797713180591242
Original Standard Deviation = 0.2833195607347249
Normalized Data = [ 1.83378808e+00  7.29815973e-01 -1.25220106e-01 -5.02803811e-01
  9.24039241e-01  1.61818244e-01 -1.47276604e+00  9.00081214e-01
  7.41427446e-01  1.02084363e-01 -1.48005398e+00  1.13948456e+00
 -1.43674436e+00 -3.53411502e-01 -1.69147197e+00 -5.13396089e-01
 -1.04609419e+00 -1.10884147e+00 -1.14017611e+00 -6.47901019e-01
 -1.02943666e+00  8.70663852e-01 -1.09247691e+00 -8.48640355e-01
 -1.44078499e-02  5.22083312e-01  4.80518235e-01 -5.72076221e-01
 -1.21804706e+00 -5.12197477e-01  1.74848633e+00 -5.42591785e-01
 -1.62524652e-03  1.44137564e+00 -6.02308137e-01 -8.49126772e-02
 -1.53083985e+00  4.35696260e-01 -3.30072020e-01 -1.50325265e+00
 -3.78502384e-03 -1.15636853e+00 -1.61567457e+00 -1.34406361e+00
  2.06357420e-02  1.09221285e+00 -1.06114279e+00  1.38740063e+00
  1.64564182e+00 -6.60849328e-01  1.79795581e-01 -1.15186466e-01
  4.87679610e-03  7.92454888e-01 -5.44785790e-01  1.3

### RESULT

Thus, the given Python program was successfully executed.

## 2. Sum of Squares of Non-zero Matrix Elements

### AIM

To generate a 50 × 50 integer matrix and compute the sum of squares of all non-zero elements using a generator expression.

### PROGRAM

In [2]:
import numpy as np

A = np.random.randint(-5, 5, (50, 50))
energy = sum(x**2 for x in A.flatten() if x != 0)
print("Energy:", energy)

Energy: 20859


### RESULT

Thus, the given Python program was successfully executed.

## 3. Monte-Carlo Estimation of π

### AIM

To estimate the value of π using randomly generated points and the Monte-Carlo method.

### PROGRAM

In [3]:
import numpy as np

N = 10000

points = ((np.random.rand(), np.random.rand()) for _ in range(N))

inside = sum(1 for x, y in points if x*x + y*y <= 1)

pi_est = 4 * inside / N

print("Estimated Pi:", pi_est)

Estimated Pi: 3.148


### RESULT

Thus, the given Python program was successfully executed.

## 4. Stability of Random 3 × 3 Matrices

### AIM

To generate 10 random 3 × 3 matrices and retain the matrices whose eigenvalues all have magnitude less than 1.

### PROGRAM

In [4]:
import numpy as np

# Generate 10 random 3x3 matrices
matrices = [np.random.randn(3, 3) for _ in range(10)]

# Select only stable matrices
stable = (A for A in matrices if np.all(np.abs(np.linalg.eigvals(A)) < 1))

# Print each stable matrix
for s in stable:
    print("Stable Matrix:\n", s)

Stable Matrix:
 [[ 0.18414627  0.85314885  0.05299558]
 [ 0.00373117 -0.30526883 -0.89511997]
 [-0.71863229 -0.06192836 -0.05611219]]
Stable Matrix:
 [[ 0.91030831 -0.67827855 -0.82206093]
 [-0.02457204 -0.02663822 -0.06407249]
 [ 0.1205906  -1.51965866  0.20002209]]
Stable Matrix:
 [[-0.60568293 -0.03043382 -0.15928558]
 [-1.05809659 -0.90128728  0.78402695]
 [ 0.24558339 -0.39749144 -0.86923354]]


### RESULT

Thus, the given Python program was successfully executed.

## 5. Sliding Windows and Covariance

### AIM

To generate a time series of 200 values, create sliding windows of length 10, and compute np.cov(w) for each window.

### PROGRAM

In [5]:
import numpy as np

data = np.random.rand(200)

windows = (data[i:i+10] for i in range(len(data)-9))

covariances = [np.cov(w) for w in windows]

print(covariances)

[array(0.07499839), array(0.08911927), array(0.09022076), array(0.10594144), array(0.10466988), array(0.09728569), array(0.12366725), array(0.11581602), array(0.07824924), array(0.07663205), array(0.09444002), array(0.11139241), array(0.0957819), array(0.07537803), array(0.07162244), array(0.0666244), array(0.08682296), array(0.09210045), array(0.10119774), array(0.1263746), array(0.12924587), array(0.10261325), array(0.12446437), array(0.1209836), array(0.11175474), array(0.07955825), array(0.07270427), array(0.04082526), array(0.07125407), array(0.0624753), array(0.06506788), array(0.06462603), array(0.06256293), array(0.08835233), array(0.08983951), array(0.09371564), array(0.09417142), array(0.07573986), array(0.07567367), array(0.08293081), array(0.07144824), array(0.06312048), array(0.08485494), array(0.06736027), array(0.07740555), array(0.08422005), array(0.08686144), array(0.0846656), array(0.0779857), array(0.08859029), array(0.08844888), array(0.08037714), array(0.05775029),

### RESULT

Thus, the given Python program was successfully executed.

## 6. Mean, Variance and Median of 500 Random Values

### AIM

To generate 500 random values using a generator expression and calculate their mean, variance, and median.

### PROGRAM

In [6]:
import numpy as np

# Generate 500 random numbers using a generator expression
data = np.fromiter((np.random.rand() for _ in range(500)), dtype=float)

# Compute mean, variance, and median
print("Mean:", np.mean(data))
print("Variance:", np.var(data))
print("Median:", np.median(data))

Mean: 0.48927985288679054
Variance: 0.08419771721410597
Median: 0.4988251563634224


### RESULT

Thus, the given Python program was successfully executed.

## 7. Pairs of Highly Correlated Feature Vectors

### AIM

To generate 20 random feature vectors of dimension 5 and identify pairs whose correlation coefficient is greater than 0.9.

### PROGRAM

In [7]:
import numpy as np
from itertools import combinations

vectors = np.random.rand(20, 5)

pairs = ((i, j) for i, j in combinations(range(20), 2)
         if np.corrcoef(vectors[i], vectors[j])[0, 1] > 0.9)

print(list(pairs))

[(1, 9), (1, 19), (4, 8), (9, 19)]


### RESULT

Thus, the given Python program was successfully executed.

## 8. Principal Component Analysis (PCA)

### AIM

To create a 100 × 5 dataset, calculate its covariance matrix, find the first principal component, and project the centered data onto it.

### PROGRAM

In [8]:
import numpy as np

X = np.random.rand(100, 5)

X_centered = X - np.mean(X, axis=0)

cov = np.cov(X_centered, rowvar=False)

eigvals, eigvecs = np.linalg.eig(cov)

pc1 = eigvecs[:, np.argmax(eigvals)]

projection = X_centered @ pc1

print(projection)

[ 0.34708696 -0.01936819 -0.40937061  0.11294141 -0.28011876  0.05572792
  0.0807312  -0.25978842  0.09569211  0.01483212 -0.23269837  0.33156485
 -0.56362834 -0.4624371  -0.29294715  0.22838843  0.41819814  0.20810846
 -0.2775483   0.12800279  0.26547401 -0.11731971  0.03203998 -0.04669936
  0.5555659  -0.1304103   0.54603956 -0.51143548 -0.28913827  0.52234886
  0.28338926  0.06966491 -0.39088839 -0.54927158 -0.23397562  0.34579602
  0.32606611 -0.35597617  0.31661128  0.21721604  0.31891663 -0.37552937
 -0.09274028 -0.46170855  0.31533143  0.42524797 -0.607177   -0.07834062
 -0.53508738 -0.05201638  0.31558233 -0.33268923 -0.20915973 -0.28841734
  0.35369896  0.49243723  0.26937433  0.32147194 -0.04501199  0.24836738
  0.04060295  0.09994582  0.01389749 -0.30494396 -0.05738671 -0.24758703
  0.14427867  0.0371195   0.10018386  0.01646592  0.37661725  0.17746753
 -0.5130742   0.29344941 -0.73956746 -0.54307035 -0.23887272  0.10447512
 -0.6833513   0.21239541 -0.23896566  0.23187821  0

### RESULT

Thus, the given Python program was successfully executed.

## 9. Most Influential Node from a Dominant Eigenvector

### AIM

To generate a 6 × 6 adjacency matrix, compute its eigenvalues and eigenvectors, and identify the node with the largest component in the dominant eigenvector.

### PROGRAM

In [9]:
import numpy as np

A = np.random.randint(0, 2, (6, 6))

eigvals, eigvecs = np.linalg.eig(A)

dominant = eigvecs[:, np.argmax(eigvals)]

node = max((i for i in range(len(dominant))),
           key=lambda i: abs(dominant[i]))

print("Most influential node:", node)

Most influential node: 3


### RESULT

Thus, the given Python program was successfully executed.