# 1. Square and Cube of Matrix Elements

**AIM**: To create a 3 × 3 matrix using numbers from 1 to 9 and find the square and cube of each element.

In [1]:
import numpy as np

A = np.arange(1, 10).reshape(3, 3)

square = A ** 2
cube = A ** 3

print(square)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [2]:
print(cube)

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


**RESULT:** Thus, the given Python program was successfully executed.

# 2. Row Sum and Column Sum

**AIM**: To create a 4 × 4 matrix using numbers from 1 to 16 and find the row sums and column sums.

In [3]:
import numpy as np

A = np.arange(1, 17).reshape(4, 4)

row_sum = np.sum(A, axis=1)
col_sum = np.sum(A, axis=0)

print(row_sum)
print(col_sum)

[10 26 42 58]
[28 32 36 40]


**RESULT:** Thus, the given Python program was successfully executed.

# 3. 3. Block Matrix

**AIM:** To construct the block matrix \\begin{bmatrix}A&B\\B&A\end{bmatrix} using two given 2 × 2 matrices.

In [4]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.block([[A, B],
              [B, A]])

print(C)

[[1 2 5 6]
 [3 4 7 8]
 [5 6 1 2]
 [7 8 3 4]]


**RESULT:** Thus, the given Python program was successfully executed.

# 4. Matrix Multiplication

**AIM:** To compute the matrix multiplication of two given matrices using NumPy.

In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.matmul(A, B)

print(C)

[[ 58  64]
 [139 154]]


**RESULT:** Thus, the given Python program was successfully executed.

# 5. Random Matrix, Sums and Square

**AIM:**
To generate a 5 × 5 random integer matrix between 1 and 50 and find its row sum, column sum, and square of all elements.

In [6]:
import numpy as np

A = np.random.randint(1, 51, size=(5, 5))

row_sum = np.sum(A, axis=1)
col_sum = np.sum(A, axis=0)
square = A ** 2

print(A)

[[ 9 26 12 26 50]
 [46  9 10 19 41]
 [ 5 48 39 30 47]
 [25  7 16  1  7]
 [40 36 10 30 16]]


In [7]:
print("Row sums :",row_sum)

Row sums : [123 125 169  56 132]


In [8]:
print("Column sums: ", col_sum)

Column sums:  [125 126  87 106 161]


In [9]:
print("Square of all elements :\n",square)

Square of all elements :
 [[  81  676  144  676 2500]
 [2116   81  100  361 1681]
 [  25 2304 1521  900 2209]
 [ 625   49  256    1   49]
 [1600 1296  100  900  256]]


**RESULT:** Thus, the given Python program was successfully executed.

# 6. Reshape Matrix and Cube

**AIM:** To create a matrix using numbers from 1 to 12, reshape it into a 3 × 4 matrix, and find the cube of all elements

In [10]:
import numpy as np

A = np.arange(1, 13).reshape(3, 4)

cube = A ** 3

print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(cube)

[[   1    8   27   64]
 [ 125  216  343  512]
 [ 729 1000 1331 1728]]


**RESULT:** Thus, the given Python program was successfully executed.

# 7. Random Matrix Multiplication

**AIM:** To generate two random 3 × 3 matrices and compute their matrix multiplication.

In [12]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

C = np.matmul(A, B)

print(A)

[[4 4 9]
 [2 6 4]
 [2 1 3]]


In [13]:
print(B)

[[1 5 1]
 [4 1 3]
 [8 2 2]]


In [14]:
print(C)

[[92 42 34]
 [58 24 28]
 [30 17 11]]


**RESULT:** Thus, the given Python program was successfully executed.

# 8. Matrix Slicing

**AIM:** To create a 4 × 4 matrix using numbers from 1 to 16 and extract the first two rows and last two columns

In [15]:
import numpy as np

A = np.arange(1, 17).reshape(4, 4)

extracted = A[0:2, 2:4]

print(extracted)

[[3 4]
 [7 8]]


**RESULT:** Thus, the given Python program was successfully executed.

# 9. Block Matrix Using Identity and Zero Matrix

**AIM:** To create the block matrix \begin{bmatrix}0&I\\I&0\end{bmatrix} where I is a 2 × 2 identity matrix

In [16]:
import numpy as np

I = np.eye(2)
Z = np.zeros((2, 2))

A = np.block([[Z, I],
              [I, Z]])

print(I)

[[1. 0.]
 [0. 1.]]


In [17]:
print(Z)

[[0. 0.]
 [0. 0.]]


In [18]:
print(A)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


**RESULT:** Thus, the given Python program was successfully executed.

# 10. Random Matrix Operations and Reshaping

**AIM:** To generate a 4 × 4 random matrix, find its row sums, column sums, square root of elements, and reshape it into 2 × 8.

In [19]:
import numpy as np

A = np.random.rand(4, 4)

row_sum = np.sum(A, axis=1)
col_sum = np.sum(A, axis=0)
sqrt_A = np.sqrt(A)
B = A.reshape(2, 8)

print(A)

[[0.63890974 0.77294699 0.34591252 0.59220326]
 [0.00885123 0.04760661 0.7395532  0.49262547]
 [0.9384987  0.33713621 0.92254327 0.87369315]
 [0.93385074 0.07724485 0.86337842 0.59822017]]


In [20]:
print("Row sums :",row_sum)

Row sums : [2.34997252 1.2886365  3.07187134 2.47269419]


In [21]:
print("Column sums :",col_sum)

Column sums : [2.52011041 1.23493466 2.87138742 2.55674206]


In [22]:
print("Square root of elements :", sqrt_A)

Square root of elements : [[0.7993183  0.87917404 0.58814328 0.76954744]
 [0.09408096 0.21818938 0.85997279 0.70187283]
 [0.96876143 0.58063431 0.96049116 0.93471555]
 [0.96635953 0.27792958 0.92918159 0.77344694]]


In [23]:
print("16 Reshaped (2 x 8 ) :\n", B)

16 Reshaped (2 x 8 ) :
 [[0.63890974 0.77294699 0.34591252 0.59220326 0.00885123 0.04760661
  0.7395532  0.49262547]
 [0.9384987  0.33713621 0.92254327 0.87369315 0.93385074 0.07724485
  0.86337842 0.59822017]]


**RESULT:** Thus, the given Python program was successfully executed.