# Lab 9: Advanced Numerical Simulation and Statistical Analysis Using NumPy and Generator Expressions

## Program 1: Random Sensor Readings and Normalization

### Aim

To generate 1000 random sensor readings and normalize them using the mean and standard deviation.

### Program

In [1]:
import numpy as np

# Generate 1000 random numbers
data = np.fromiter((np.random.rand() for _ in range(1000)), dtype=float)

# Compute mean and standard deviation of original data
mean = np.mean(data)
std = np.std(data)

# Normalize the data
normalized = (data - mean) / std

# Print results
print("Original Mean =", mean)
print("Original Standard Deviation =", std)
print("Normalized Data =", normalized)

# Check mean and standard deviation of normalized data
print("Normalized Mean =", np.mean(normalized))
print("Normalized Standard Deviation =", np.std(normalized))
print(np.isclose(np.mean(normalized), 0))
print(round(np.mean(normalized), 10))

Original Mean = 0.49971810922709675
Original Standard Deviation = 0.2842653206510492
Normalized Data = [ 0.9167914   0.07112228  0.07230593  0.79548011  1.31980338  0.44610435
 -1.25301288 -0.9627841  -0.06610858 -0.28911292 -1.65461842  1.72123451
 -0.54570191  1.67063388 -0.4892671  -0.49878101 -1.56483822  1.45027752
  0.50811783  1.17944172 -0.82069608  0.58827523  0.71613598 -0.98834344
  0.95782822  1.74248801 -1.09346195 -0.03370593  0.42484714 -0.89826978
 -0.44650308 -0.84596199 -1.64991499 -0.20929509 -0.31156927  0.70631598
 -0.59493874 -1.65098567  1.34598071 -0.89341277 -0.71851217  0.23506773
  0.43431472 -0.46226358  0.11473228  0.58277154  1.58159179 -1.695455
  1.75863481 -0.96575996  0.63061302 -0.10394886 -1.66177289 -1.10289123
 -0.47676975  0.85506192 -0.94422142  0.00458539  0.26452309  0.2741721
  0.9623643  -0.80259827 -1.21333367 -0.611326   -0.59289555 -1.71454695
  1.01597939  0.33622869 -1.32963324 -1.48299739  0.43159789  0.89824428
 -0.85616657 -0.16798015

### Result

Thus, the given Python program was successfully executed.

## Program 2: Sum of Squares of Non-zero Matrix Elements

### Aim

To generate a 50 × 50 integer matrix and calculate the sum of squares of its non-zero elements.

### Program

In [2]:
import numpy as np

A = np.random.randint(-5, 5, (50, 50))
energy = sum(x**2 for x in A.flatten() if x != 0)
print("Energy:", energy)

Energy: 21826


### Result

Thus, the given Python program was successfully executed.

## Program 3: Monte-Carlo Estimation of Pi

### Aim

To estimate the value of pi by generating random points and counting those inside a unit circle.

### Program

In [3]:
import numpy as np

N = 10000
points = ((np.random.rand(), np.random.rand()) for _ in range(N))
inside = sum(1 for x, y in points if x*x + y*y <= 1)
pi_est = 4 * inside / N

print("Estimated Pi:", pi_est)

Estimated Pi: 3.1224


### Result

Thus, the given Python program was successfully executed.

## Program 4: Stability of Random 3 × 3 Matrices

### Aim

To generate 10 random 3 × 3 matrices and display matrices whose eigenvalues all have magnitude less than 1.

### Program

In [4]:
import numpy as np

# Generate 10 random 3x3 matrices
matrices = [np.random.randn(3, 3) for _ in range(10)]

# Select only stable matrices
stable = (A for A in matrices if np.all(np.abs(np.linalg.eigvals(A)) < 1))

# Print each stable matrix
for s in stable:
    print("Stable Matrix:\n", s)

Stable Matrix:
 [[-0.12160575  1.22208327  1.1181796 ]
 [ 0.08467328  0.26837808  0.62413821]
 [ 0.03297314 -0.82322296 -0.45067356]]
Stable Matrix:
 [[ 0.42161264 -2.33694794 -0.51724673]
 [ 0.69495697 -1.38556699  0.01764607]
 [ 0.10648996  0.3335019  -0.07646256]]
Stable Matrix:
 [[-1.26347729 -0.1886716  -1.20636105]
 [ 0.6159641   0.35491193 -0.3426939 ]
 [ 1.35576208  0.0924897   1.11108649]]
Stable Matrix:
 [[-0.05547822  0.03493985 -0.08953179]
 [ 0.85332948 -0.29617823  0.8290937 ]
 [ 0.08480479  0.05359313  0.11481479]]


### Result

Thus, the given Python program was successfully executed.

## Program 5: Sliding Windows and Covariance

### Aim

To create length-10 sliding windows from 200 random values and calculate the covariance/variance for each window.

### Program

In [5]:
import numpy as np

data = np.random.rand(200)
windows = (data[i:i+10] for i in range(len(data)-9))
covariances = [np.cov(w) for w in windows]

print(covariances)

[array(0.04398058), array(0.04704257), array(0.0587587), array(0.06969343), array(0.07295164), array(0.09980489), array(0.09865325), array(0.10413644), array(0.10403226), array(0.10110106), array(0.080983), array(0.07567821), array(0.06618755), array(0.07338818), array(0.07988177), array(0.06490199), array(0.08415385), array(0.07825554), array(0.08246567), array(0.09783836), array(0.09433364), array(0.09740484), array(0.09764377), array(0.07461961), array(0.05755986), array(0.05539072), array(0.0417666), array(0.04224082), array(0.05234968), array(0.06302674), array(0.06184948), array(0.06337096), array(0.062574), array(0.08299847), array(0.08938738), array(0.08445371), array(0.09689241), array(0.09669522), array(0.08363962), array(0.06896272), array(0.07841754), array(0.07416373), array(0.07319439), array(0.07342137), array(0.05356664), array(0.0426376), array(0.04908385), array(0.04959086), array(0.06362411), array(0.06575877), array(0.05871074), array(0.05928488), array(0.05120963),

### Result

Thus, the given Python program was successfully executed.

## Program 6: Mean, Variance and Median of 500 Random Values

### Aim

To generate 500 random values and calculate their mean, variance, and median.

### Program

In [6]:
import numpy as np

# Generate 500 random numbers using a generator expression
data = np.fromiter((np.random.rand() for _ in range(500)), dtype=float)

# Compute mean, variance, and median
print("Mean:", np.mean(data))
print("Variance:", np.var(data))
print("Median:", np.median(data))

Mean: 0.5095692889905568
Variance: 0.08186255562905541
Median: 0.5241443916371349


### Result

Thus, the given Python program was successfully executed.

## Program 7: Pairs of Highly Correlated Feature Vectors

### Aim

To generate 20 random feature vectors and identify pairs with a correlation coefficient greater than 0.9.

### Program

In [7]:
import numpy as np
from itertools import combinations

vectors = np.random.rand(20, 5)
pairs = ((i, j) for i, j in combinations(range(20), 2)
         if np.corrcoef(vectors[i], vectors[j])[0, 1] > 0.9)

print(list(pairs))

[(1, 12), (2, 5), (7, 8), (9, 15)]


### Result

Thus, the given Python program was successfully executed.

## Program 8: Principal Component Analysis (PCA)

### Aim

To calculate the covariance matrix of a 100 × 5 dataset and project the centered data onto the first principal component.

### Program

In [8]:
import numpy as np

X = np.random.rand(100, 5)
X_centered = X - np.mean(X, axis=0)
cov = np.cov(X_centered, rowvar=False)
eigvals, eigvecs = np.linalg.eig(cov)
pc1 = eigvecs[:, np.argmax(eigvals)]
projection = X_centered @ pc1

print(projection)

[ 0.05354788 -0.6042408   0.15566616  0.14370678 -0.30169168  0.09145753
 -0.51408497 -0.23984711  0.46116215 -0.37141207  0.02963886 -0.23193134
 -0.37595202 -0.23617349  0.2264536   0.59194518  0.16605092  0.06888452
  0.18890417  0.10847021 -0.38003955 -0.35813844  0.20651358 -0.05865729
 -0.09017099  0.37123608 -0.07555823  0.54064851 -0.27582326  0.40694081
  0.46267911 -0.07329814  0.3996959   0.06927951  0.36536628 -0.07470848
 -0.30530227  0.14433473  0.25004842 -0.75433245  0.16574031  0.40230186
  0.10783907  0.0152414   0.60310625 -0.09547438  0.07800946 -0.27747239
  0.06558171 -0.22532604  0.17859261 -0.19054008 -0.40042139 -0.15766206
  0.22671453 -0.40918913  0.2628039  -0.19912163 -0.53025126  0.45291195
 -0.24968405  0.2324139  -0.15254661 -0.13942309 -0.14023705 -0.11146803
  0.23635836 -0.23535155  0.02839315  0.0395969  -0.73636464 -0.51179272
  0.38515169 -0.34978344  0.4035733  -0.27491639 -0.01114784 -0.33711376
  0.55457522 -0.27223219  0.55782983 -0.17770091 -0

### Result

Thus, the given Python program was successfully executed.

## Program 9: Most Influential Node from a Dominant Eigenvector

### Aim

To generate a 6 × 6 adjacency matrix and identify the node with the largest absolute component in the selected dominant eigenvector.

### Program

In [9]:
import numpy as np

A = np.random.randint(0, 2, (6, 6))
eigvals, eigvecs = np.linalg.eig(A)
dominant = eigvecs[:, np.argmax(eigvals)]
node = max((i for i in range(len(dominant))),
           key=lambda i: abs(dominant[i]))

print("Most influential node:", node)

Most influential node: 5


### Result

Thus, the given Python program was successfully executed.

# Program 10: Broadcasting – Robot Spare-Part Billing

### Aim

To apply NumPy broadcasting to calculate final billing values after discounts and taxes and identify the group with maximum revenue.



### Program

In [10]:
import numpy as np

S = np.array([[320, 360, 400],
              [280, 310, 350],
              [450, 480, 520],
              [240, 270, 300]])

d = np.array([20, 25, 30])
t = np.array([[0.05], [0.08], [0.10], [0.06]])

final = (S - d) * (1 + t)
revenue = final.sum(axis=1)
best = np.argmax(revenue)

print("Shape:", final.shape)
print(final)
print("Revenue:", revenue)
print("Maximum group:", best + 1)

Shape: (4, 3)
[[315.   351.75 388.5 ]
 [280.8  307.8  345.6 ]
 [473.   500.5  539.  ]
 [233.2  259.7  286.2 ]]
Revenue: [1055.25  934.2  1512.5   779.1 ]
Maximum group: 3


### Result

Thus, the given Python program was successfully executed.