# Lab 10: Linear Algebra Computations Using NumPy linalg Package

## Program 1: Generator Expression and NumPy Vectorization

### Aim

To calculate the sum of ${i²/(i+1)}$ for i from 1 to 50 using a generator expression and NumPy vectorization.

### Program

In [1]:
import numpy as np

# Generator expression
gen_sum = sum(i*i/(i+1) for i in range(1, 51))

# NumPy vectorized solution
i = np.arange(1, 51)
numpy_sum = np.sum(i*i/(i+1))

print("Generator sum =", gen_sum)
print("NumPy sum     =", numpy_sum)
print("Equal?        =", np.isclose(gen_sum, numpy_sum))

Generator sum = 1228.5188131814666
NumPy sum     = 1228.5188131814666
Equal?        = True


### Result

Thus, the given Python program was successfully executed.

## Program 2: Invertibility, Determinant and Matrix Inverse

### Aim

To check whether a random 4 × 4 matrix is invertible and verify its inverse.

### Program

In [2]:
import numpy as np

A = np.random.rand(4, 4)
det_A = np.linalg.det(A)

print("A =\n", A)
print("det(A) =", det_A)

if abs(det_A) > 1e-10:
    A_inv = np.linalg.inv(A)
    product = np.dot(A, A_inv)
    print("A inverse =\n", A_inv)
    print("A @ A_inverse =\n", product)
    print("Verified?", np.allclose(product, np.eye(4)))
else:
    print("Matrix is singular; inverse does not exist.")

A =
 [[0.93352767 0.08711062 0.01650631 0.41502475]
 [0.91450689 0.72761105 0.731582   0.11746699]
 [0.57095853 0.75642696 0.9606909  0.87270042]
 [0.52358598 0.32920579 0.72120133 0.60873597]]
det(A) = -0.1737531524374657
A inverse =
 [[ 0.76081788  0.50883091 -0.82054516  0.55945605]
 [ 0.16416108  0.44706268  2.55092378 -3.85526462]
 [-1.22873844  0.4881618  -1.73281131  3.22773616]
 [ 0.71257731 -1.25777894  1.37917407 -0.57758292]]
A @ A_inverse =
 [[ 1.00000000e+00  4.73214434e-17  3.64956297e-17 -2.40106545e-17]
 [-7.46875954e-17  1.00000000e+00  7.71734079e-17  1.35071266e-16]
 [-2.15448356e-16  4.19361394e-18  1.00000000e+00 -8.09369782e-17]
 [-2.21265981e-17  8.16503293e-17 -4.63741803e-18  1.00000000e+00]]
Verified? True


### Result

Thus, the given Python program was successfully executed.

## Program 3: Singular Matrix with Zero Determinant

### Aim

To construct a singular matrix, verify that its determinant is zero, and show that its inverse does not exist.

### Program

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 1, 1]], dtype=float)

det_A = np.linalg.det(A)
print("A =\n", A)
print("det(A) =", det_A)
print("Numerically zero?", np.isclose(det_A, 0))

if np.isclose(det_A, 0):
    print("A is singular, so A inverse does not exist.")

A =
 [[1. 2. 3.]
 [2. 4. 6.]
 [1. 1. 1.]]
det(A) = 0.0
Numerically zero? True
A is singular, so A inverse does not exist.


### Result

Thus, the given Python program was successfully executed.

## Program 4: Eigenvalues and Eigenvectors

### Aim

To calculate the eigenvalues and eigenvectors of a matrix and verify the equation Av = λv.

### Program

In [4]:
import numpy as np

A = np.array([[4, 2],
              [1, 3]], dtype=float)

values, vectors = np.linalg.eig(A)

print("Eigenvalues =", values)
print("Eigenvectors =\n", vectors)

for k in range(len(values)):
    v = vectors[:, k]
    lam = values[k]
    print("\nEigenvalue:", lam)
    print("A v      =", np.dot(A, v))
    print("lambda v =", lam * v)
    print("Verified?", np.allclose(np.dot(A, v), lam * v))

Eigenvalues = [5. 2.]
Eigenvectors =
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Eigenvalue: 5.0
A v      = [4.47213595 2.23606798]
lambda v = [4.47213595 2.23606798]
Verified? True

Eigenvalue: 2.0
A v      = [-1.41421356  1.41421356]
lambda v = [-1.41421356  1.41421356]
Verified? True


### Result

Thus, the given Python program was successfully executed.

## Program 5: Linear System with No Unique Solution

### Aim

To solve a consistent linear system with infinitely many solutions using NumPy and interpret its rank.

### Program

In [5]:
import numpy as np

A = np.array([[1, 1, 1],
              [2, 2, 2]], dtype=float)
b = np.array([3, 6], dtype=float)

x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print("One NumPy solution =", x)
print("A @ x =", A @ x)
print("b     =", b)
print("Rank(A) =", rank)
print("Residuals =", residuals)

if rank < A.shape[1]:
    print("No unique solution: infinitely many solutions exist.")

One NumPy solution = [1. 1. 1.]
A @ x = [3. 6.]
b     = [3. 6.]
Rank(A) = 1
Residuals = []
No unique solution: infinitely many solutions exist.


### Result

Thus, the given Python program was successfully executed.

## Program 6: Rank and Linear Dependence of Rows

### Aim

To find the rank of a matrix and identify the linear dependence between its rows.

### Program

In [6]:
import numpy as np

A = np.array([[1, 2],
              [2, 4]])

rank_A = np.linalg.matrix_rank(A)
print("A =\n", A)
print("Rank(A) =", rank_A)

if rank_A < min(A.shape):
    print("Rows/columns are linearly dependent.")
    print("Here Row 2 = 2 * Row 1.")

A =
 [[1 2]
 [2 4]]
Rank(A) = 1
Rows/columns are linearly dependent.
Here Row 2 = 2 * Row 1.


### Result

Thus, the given Python program was successfully executed.

## Program 7: Non-Commutativity of Matrix Multiplication

### Aim

To compute AB and BA for two random matrices and verify that matrix multiplication is generally non-commutative.

### Program

In [7]:
import numpy as np

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

AB = np.dot(A, B)
BA = np.dot(B, A)

print("A =\n", A)
print("B =\n", B)
print("AB =\n", AB)
print("BA =\n", BA)
print("AB = BA ?", np.allclose(AB, BA))

A =
 [[0.88439146 0.71999591 0.54379594]
 [0.4179787  0.58227894 0.88014685]
 [0.52197976 0.9751439  0.22849014]]
B =
 [[0.95477082 0.17344784 0.5736331 ]
 [0.01153925 0.02993232 0.93773703]
 [0.06496347 0.97805581 0.09198301]]
AB =
 [[0.88802625 0.70680972 1.23250303]
 [0.46297033 0.9507592  0.8667495 ]
 [0.52446699 0.34320069 1.23487063]]
BA =
 [[1.21631353 1.34780093 0.80292958]
 [0.51219604 0.94016572 0.2468835 ]
 [0.51427291 0.7059714  0.91717682]]
AB = BA ? False


### Result

Thus, the given Python program was successfully executed.

## Program 8: Block Diagonal Matrix and Its Determinant

### Aim

To construct a block diagonal matrix and verify that its determinant equals the product of the determinants of its diagonal blocks.

### Program

In [8]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

Z = np.zeros((2, 2))
M = np.block([[A, Z],
              [Z, B]])

det_M = np.linalg.det(M)
product = np.linalg.det(A) * np.linalg.det(B)

print("Block matrix M =\n", M)
print("det(M) =", det_M)
print("det(A) det(B) =", product)
print("Verified?", np.isclose(det_M, product))

Block matrix M =
 [[1. 2. 0. 0.]
 [3. 4. 0. 0.]
 [0. 0. 5. 6.]
 [0. 0. 7. 8.]]
det(M) = 4.0000000000000115
det(A) det(B) = 4.000000000000011
Verified? True


### Result

Thus, the given Python program was successfully executed.

## Program 9: Symmetric Matrix and Orthogonal Eigenvectors

### Aim

To calculate the eigenvalues of a symmetric matrix and verify that its eigenvectors are orthogonal.

### Program

In [9]:
import numpy as np

A = np.array([[2, 1],
              [1, 2]], dtype=float)

values, vectors = np.linalg.eig(A)

v1 = vectors[:, 0]
v2 = vectors[:, 1]
dot_product = np.dot(v1, v2)

print("Eigenvalues =", values)
print("Eigenvectors =\n", vectors)
print("v1 . v2 =", dot_product)
print("Orthogonal?", np.isclose(dot_product, 0))

Eigenvalues = [3. 1.]
Eigenvectors =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
v1 . v2 = 0.0
Orthogonal? True


### Result

Thus, the given Python program was successfully executed.

## Program 10: Performance: Python Loops versus NumPy Vectorization

### Aim

To compare the execution time of squaring a 1000 × 1000 matrix using Python loops and NumPy vectorization.

### Program

In [10]:
import numpy as np
import time

A = np.random.rand(1000, 1000)

# NumPy vectorization
start = time.time()
B = A * A
numpy_time = time.time() - start

# Python nested loops / list comprehension
start = time.time()
C = [[A[i, j] * A[i, j] for j in range(1000)]
     for i in range(1000)]
loop_time = time.time() - start

print("NumPy time =", numpy_time, "seconds")
print("Loop time =", loop_time, "seconds")
print("Same result?", np.allclose(B, np.array(C)))

if numpy_time > 0:
    print("Speed-up factor =", loop_time / numpy_time)

NumPy time = 0.004002809524536133 seconds
Loop time = 0.47124505043029785 seconds
Same result? True
Speed-up factor = 117.7285722794687


### Result

Thus, the given Python program was successfully executed.